const ApiEndpoints = {
  company: 'company',
  comicStrip: 'comicStrip',
  organization: 'organization',
  soundtrack: 'soundtrack',
  character: 'character',
  literature: 'literature',
  magazine: 'magazine',
  videoRelease: 'videoRelease',
  animal: 'animal',
  comicCollection: 'comicCollection',
  staff: 'staff',
  common: 'common',
  title: 'title',
  astronomicalObject: 'astronomicalObject',
  element: 'element',
  tradingCard: 'tradingCard',
  comics: 'comics',
  tradingCardDeck: 'tradingCardDeck',
  magazineSeries: 'magazineSeries',
  videoGame: 'videoGame',
  technology: 'technology',
  comicSeries: 'comicSeries',
  movie: 'movie',
  performer: 'performer',
  weapon: 'weapon',
  episode: 'episode',
  season: 'season',
  bookSeries: 'bookSeries',
  conflict: 'conflict',
  location: 'location',
  spacecraftClass: 'spacecraftClass',
  material: 'material',
  species: 'species',
  occupation: 'occupation',
  bookCollection: 'bookCollection',
  medicalCondition: 'medicalCondition',
  food: 'food',
  tradingCardSet: 'tradingCardSet',
  book: 'book',
  spacecraft: 'spacecraft',
  series: 'series',
};

export const RESOURCE_OPTIONS = Object.entries(ApiEndpoints).map(([value]) => ({
  key: value,
  value,
}));
